language: clojure
lein: lein
jdk:
  - oraclejdk8

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

env:
  - YETIBOT_DB_URL="postgresql://postgres@localhost:5432/yetibot"

script: lein test

services:
  - postgresql
